"""empty message

Revision ID: 620fe2ef4a02
Revises: 4927b3ebe49c
Create Date: 2026-08-31 18:00:29.835343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620fe2ef4a02'
down_revision: Union[str, Sequence[str], None] = '4927b3ebe49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))

    op.create_unique_constraint('uq_users_username', 'users', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('users')
    # ### end Alembic commands ###
